name: 📊 Static Checks
on: [push, pull_request]

jobs:
  format:
    name: File formatting (file_format.sh)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix moreutils

      - name: File formatting checks (file_format.sh)
        run: |
          bash ./.github/workflows/file_format.sh
